#!/usr/bin/env sh

current_branch=$(git branch --show-current)

branch_number=$(echo "$current_branch" | sed 's/[^0-9]*//g')

commit_message_file="$1"
commit_message=$(cat "$commit_message_file")

if [[ ! $commit_message = *"$branch_number"* ]]; then
  echo "ERROR: Commit message must include '$branch_number'"
  exit 1
fi